GET http://localhost:4000/user HTTP/1.1

###

POST http://localhost:4000/auth/register HTTP/1.1
Content-Type: application/json

{
    "lastName" : "JOUARE",
    "firstName" : "Anaïs",
    "password" : "roxane23",
    "email" : "anais.jouaret@gmail.com",
    "github" :"bcjds",
    "linkedin" : "niocdksnlkd"
}
###

POST http://localhost:4000/auth/login HTTP/1.1
Content-Type: application/json

{
    "email" : "anais.jouaret@gmail.com",
    "password" : "roxane23"
}

###
DELETE http://localhost:4000/user/685cc979-e6bf-41f5-80ed-31087bec3f22 HTTP/1.1
Authorization : Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY4NWNjOTc5LWU2YmYtNDFmNS04MGVkLTMxMDg3YmVjM2YyMiIsImVtYWlsIjoiYW5haXMuam91YXJldEBnbWFpbC5jb20iLCJpYXQiOjE1OTYwMTU4NjEsImV4cCI6MTU5NjEwMjI2MX0.FQdkvzlvZWPbWppPhjSOYYBO7ihwqixdE9Kut8tIEMQ
